// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceCatalogueManager.Api.Data.DbContext;

#nullable disable

namespace ServiceCatalogueManager.Api.Migrations
{
    [DbContext(typeof(ServiceCatalogDbContext))]
    partial class ServiceCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.AccessRequirement", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessId"));

                    b.Property<string>("AccessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InteractionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("AccessId");

                    b.HasIndex("InteractionId");

                    b.ToTable("AccessRequirement", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.CloudProviderCapability", b =>
                {
                    b.Property<int>("CapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapabilityId"));

                    b.Property<string>("CapabilityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapabilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CloudProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CapabilityId");

                    b.HasIndex("CloudProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("CloudProviderCapabilities");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.CustomerRequirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"));

                    b.Property<int>("InteractionId")
                        .HasColumnType("int");

                    b.Property<string>("RequirementDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RequirementId");

                    b.HasIndex("InteractionId");

                    b.ToTable("CustomerRequirement", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.EffortEstimationItem", b =>
                {
                    b.Property<int>("EstimationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstimationId"));

                    b.Property<int>("EffortCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("EffortDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SizeOptionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("EstimationId");

                    b.HasIndex("EffortCategoryId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SizeOptionId");

                    b.ToTable("EffortEstimationItem", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_CloudProvider", b =>
                {
                    b.Property<int>("CloudProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CloudProviderId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CloudProviderId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_CloudProvider", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_DependencyType", b =>
                {
                    b.Property<int>("DependencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependencyTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("DependencyTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_DependencyType", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_EffortCategory", b =>
                {
                    b.Property<int>("EffortCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EffortCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("EffortCategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_EffortCategory", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_InteractionLevel", b =>
                {
                    b.Property<int>("InteractionLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionLevelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("InteractionLevelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_InteractionLevel", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_LicenseType", b =>
                {
                    b.Property<int>("LicenseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("LicenseTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_LicenseType", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_PrerequisiteCategory", b =>
                {
                    b.Property<int>("PrerequisiteCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrerequisiteCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PrerequisiteCategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_PrerequisiteCategory", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_RequirementLevel", b =>
                {
                    b.Property<int>("RequirementLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementLevelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RequirementLevelId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_RequirementLevel", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_Role", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_ScopeType", b =>
                {
                    b.Property<int>("ScopeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScopeTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ScopeTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_ScopeType", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_ServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("LU_ServiceCategory", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", b =>
                {
                    b.Property<int>("SizeOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeOptionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("SizeOptionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_SizeOption", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_ToolCategory", b =>
                {
                    b.Property<int>("ToolCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ToolCategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LU_ToolCategory", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.PhaseDurationBySize", b =>
                {
                    b.Property<int>("PhaseDurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhaseDurationId"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("SizeOptionId")
                        .HasColumnType("int");

                    b.HasKey("PhaseDurationId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("SizeOptionId");

                    b.ToTable("PhaseDurationBySize", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ScopeDependency", b =>
                {
                    b.Property<int>("ScopeDependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScopeDependencyId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiresDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ScopeDependencyId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ScopeDependencies");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("v1.0");

                    b.HasKey("ServiceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ServiceCode")
                        .IsUnique();

                    b.ToTable("ServiceCatalogItem", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceDependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependencyId"));

                    b.Property<string>("DependencyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DependencyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DependentServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequirementLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("DependencyId");

                    b.HasIndex("DependencyTypeId");

                    b.HasIndex("DependentServiceId");

                    b.HasIndex("RequirementLevelId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceDependency", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceInput", b =>
                {
                    b.Property<int>("InputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InputId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RequirementLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("InputId");

                    b.HasIndex("RequirementLevelId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceInput", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionId"));

                    b.Property<int>("InteractionLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("InteractionId");

                    b.HasIndex("InteractionLevelId");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("ServiceInteraction", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceLicense", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseId"));

                    b.Property<string>("LicenseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LicenseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("LicenseId");

                    b.HasIndex("LicenseTypeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceLicenses");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceMultiCloudConsideration", b =>
                {
                    b.Property<int>("ConsiderationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsiderationId"));

                    b.Property<int>("CloudProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Considerations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Limitations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ConsiderationId");

                    b.HasIndex("CloudProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceMultiCloudConsideration", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceOutputCategory", b =>
                {
                    b.Property<int>("OutputCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutputCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("OutputCategoryId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceOutputCategory", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceOutputItem", b =>
                {
                    b.Property<int>("OutputItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutputItemId"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutputCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("OutputItemId");

                    b.HasIndex("OutputCategoryId");

                    b.ToTable("ServiceOutputItem", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServicePrerequisite", b =>
                {
                    b.Property<int>("PrerequisiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrerequisiteId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrerequisiteCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("PrerequisiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PrerequisiteId");

                    b.HasIndex("PrerequisiteCategoryId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServicePrerequisite", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceResponsibleRole", b =>
                {
                    b.Property<int>("ResponsibleRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponsibleRoleId"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ResponsibleRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceResponsibleRole", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceScopeCategory", b =>
                {
                    b.Property<int>("ScopeCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScopeCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScopeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ScopeCategoryId");

                    b.HasIndex("ScopeTypeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceScopeCategory", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceScopeItem", b =>
                {
                    b.Property<int>("ScopeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScopeItemId"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScopeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ScopeItemId");

                    b.HasIndex("ScopeCategoryId");

                    b.ToTable("ServiceScopeItem", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceSizeOption", b =>
                {
                    b.Property<int>("ServiceSizeOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceSizeOptionId"));

                    b.Property<string>("Complexity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DurationDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffortDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SizeOptionId")
                        .HasColumnType("int");

                    b.Property<string>("TeamSizeDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceSizeOptionId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SizeOptionId");

                    b.ToTable("ServiceSizeOption", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceTeamAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<string>("AllocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AllocationPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SizeOptionId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SizeOptionId");

                    b.ToTable("ServiceTeamAllocation", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceToolFramework", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolId"));

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("ToolCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ToolDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToolId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ToolCategoryId");

                    b.ToTable("ServiceToolFrameworks");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingCriteria", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaId"));

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CriteriaId");

                    b.HasIndex("ServiceId");

                    b.ToTable("SizingCriterias");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingCriteriaValue", b =>
                {
                    b.Property<int>("CriteriaValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaValueId"));

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<int>("SizeOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CriteriaValueId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("SizeOptionId");

                    b.ToTable("SizingCriteriaValues");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingExample", b =>
                {
                    b.Property<int>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExampleId"));

                    b.Property<string>("ExampleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SizeOptionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ExampleId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SizeOptionId");

                    b.ToTable("SizingExample", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingExampleCharacteristic", b =>
                {
                    b.Property<int>("CharacteristicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacteristicId"));

                    b.Property<string>("CharacteristicDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExampleId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CharacteristicId");

                    b.HasIndex("ExampleId");

                    b.ToTable("SizingExampleCharacteristics");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingParameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ParameterId");

                    b.HasIndex("ServiceId");

                    b.ToTable("SizingParameters");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingParameterValue", b =>
                {
                    b.Property<int>("ParameterValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterValueId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParameterValueId");

                    b.HasIndex("ParameterId");

                    b.ToTable("SizingParameterValues");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.StakeholderInvolvement", b =>
                {
                    b.Property<int>("InvolvementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvolvementId"));

                    b.Property<int>("InteractionId")
                        .HasColumnType("int");

                    b.Property<string>("InvolvementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StakeholderRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InvolvementId");

                    b.HasIndex("InteractionId");

                    b.HasIndex("RoleId");

                    b.ToTable("StakeholderInvolvement", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.TechnicalComplexityAddition", b =>
                {
                    b.Property<int>("AdditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdditionId"));

                    b.Property<string>("AdditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("AdditionId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TechnicalComplexityAdditions");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.TimelinePhase", b =>
                {
                    b.Property<int>("PhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhaseId"));

                    b.Property<string>("PhaseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PhaseId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TimelinePhase", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.UsageScenario", b =>
                {
                    b.Property<int>("ScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScenarioId"));

                    b.Property<string>("ScenarioDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScenarioNumber")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ScenarioId");

                    b.HasIndex("ServiceId");

                    b.ToTable("UsageScenario", (string)null);
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.AccessRequirement", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", "Interaction")
                        .WithMany("AccessRequirements")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.CloudProviderCapability", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_CloudProvider", "CloudProvider")
                        .WithMany()
                        .HasForeignKey("CloudProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("CloudCapabilities")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CloudProvider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.CustomerRequirement", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", "Interaction")
                        .WithMany("CustomerRequirements")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.EffortEstimationItem", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_EffortCategory", "EffortCategory")
                        .WithMany()
                        .HasForeignKey("EffortCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("EffortEstimations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", "SizeOption")
                        .WithMany()
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EffortCategory");

                    b.Navigation("Service");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_ServiceCategory", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_ServiceCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.PhaseDurationBySize", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.TimelinePhase", "Phase")
                        .WithMany("DurationsBySize")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", "SizeOption")
                        .WithMany()
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ScopeDependency", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("ScopeDependencies")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceDependency", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_DependencyType", "DependencyType")
                        .WithMany()
                        .HasForeignKey("DependencyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "DependentService")
                        .WithMany()
                        .HasForeignKey("DependentServiceId");

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_RequirementLevel", "RequirementLevel")
                        .WithMany()
                        .HasForeignKey("RequirementLevelId");

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("Dependencies")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependencyType");

                    b.Navigation("DependentService");

                    b.Navigation("RequirementLevel");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceInput", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_RequirementLevel", "RequirementLevel")
                        .WithMany()
                        .HasForeignKey("RequirementLevelId");

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("Inputs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequirementLevel");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_InteractionLevel", "InteractionLevel")
                        .WithMany()
                        .HasForeignKey("InteractionLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithOne("Interaction")
                        .HasForeignKey("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteractionLevel");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceLicense", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_LicenseType", "LicenseType")
                        .WithMany()
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("Licenses")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceMultiCloudConsideration", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_CloudProvider", "CloudProvider")
                        .WithMany()
                        .HasForeignKey("CloudProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("MultiCloudConsiderations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CloudProvider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceOutputCategory", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("OutputCategories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceOutputItem", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceOutputCategory", "OutputCategory")
                        .WithMany("Items")
                        .HasForeignKey("OutputCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutputCategory");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServicePrerequisite", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_PrerequisiteCategory", "PrerequisiteCategory")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("Prerequisites")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrerequisiteCategory");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceResponsibleRole", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("ResponsibleRoles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceScopeCategory", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_ScopeType", "ScopeType")
                        .WithMany()
                        .HasForeignKey("ScopeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("ScopeCategories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScopeType");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceScopeItem", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceScopeCategory", "ScopeCategory")
                        .WithMany("Items")
                        .HasForeignKey("ScopeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScopeCategory");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceSizeOption", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("SizeOptions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", "SizeOption")
                        .WithMany()
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceTeamAllocation", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("TeamAllocations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", "SizeOption")
                        .WithMany()
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Service");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceToolFramework", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("Tools")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_ToolCategory", "ToolCategory")
                        .WithMany()
                        .HasForeignKey("ToolCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ToolCategory");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingCriteria", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("SizingCriteria")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingCriteriaValue", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.SizingCriteria", "Criteria")
                        .WithMany("Values")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", "SizeOption")
                        .WithMany()
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingExample", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("SizingExamples")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_SizeOption", "SizeOption")
                        .WithMany()
                        .HasForeignKey("SizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("SizeOption");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingExampleCharacteristic", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.SizingExample", "Example")
                        .WithMany("Characteristics")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Example");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingParameter", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("SizingParameters")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingParameterValue", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.SizingParameter", "Parameter")
                        .WithMany("Values")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.StakeholderInvolvement", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", "Interaction")
                        .WithMany("StakeholderInvolvements")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.LU_Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.TechnicalComplexityAddition", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("ComplexityAdditions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.TimelinePhase", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("TimelinePhases")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.UsageScenario", b =>
                {
                    b.HasOne("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", "Service")
                        .WithMany("UsageScenarios")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.LU_ServiceCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceCatalogItem", b =>
                {
                    b.Navigation("CloudCapabilities");

                    b.Navigation("ComplexityAdditions");

                    b.Navigation("Dependencies");

                    b.Navigation("EffortEstimations");

                    b.Navigation("Inputs");

                    b.Navigation("Interaction");

                    b.Navigation("Licenses");

                    b.Navigation("MultiCloudConsiderations");

                    b.Navigation("OutputCategories");

                    b.Navigation("Prerequisites");

                    b.Navigation("ResponsibleRoles");

                    b.Navigation("ScopeCategories");

                    b.Navigation("ScopeDependencies");

                    b.Navigation("SizeOptions");

                    b.Navigation("SizingCriteria");

                    b.Navigation("SizingExamples");

                    b.Navigation("SizingParameters");

                    b.Navigation("TeamAllocations");

                    b.Navigation("TimelinePhases");

                    b.Navigation("Tools");

                    b.Navigation("UsageScenarios");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceInteraction", b =>
                {
                    b.Navigation("AccessRequirements");

                    b.Navigation("CustomerRequirements");

                    b.Navigation("StakeholderInvolvements");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceOutputCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.ServiceScopeCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingCriteria", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingExample", b =>
                {
                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.SizingParameter", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("ServiceCatalogueManager.Api.Data.Entities.TimelinePhase", b =>
                {
                    b.Navigation("DurationsBySize");
                });
#pragma warning restore 612, 618
        }
    }
}
