using System.Text;

namespace ServiceCatalogueManager.Api.Templates.Markdown;

public class CatalogMarkdownTemplate
{
    public static string Generate(CatalogMarkdownData data)
    {
        var sb = new StringBuilder();
        var services = data.Services?.ToList() ?? new List<CatalogServiceMdSummary>();

        // Header
        sb.AppendLine($"# {data.CatalogTitle ?? "Service Catalogue"}");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC  ");
        sb.AppendLine($"**Total Services:** {services.Count}  ");
        sb.AppendLine($"**Active:** {services.Count(s => s.IsActive)} | **Inactive:** {services.Count(s => !s.IsActive)}");
        sb.AppendLine();

        // Table of Contents
        sb.AppendLine("## Table of Contents");
        sb.AppendLine();
        sb.AppendLine("- [Summary](#summary)");
        
        var grouped = services.GroupBy(s => s.CategoryName ?? "Uncategorized").OrderBy(g => g.Key);
        foreach (var group in grouped)
        {
            var anchor = group.Key.ToLower().Replace(" ", "-").Replace("&", "").Replace("/", "");
            sb.AppendLine($"- [{group.Key}](#{anchor})");
        }
        sb.AppendLine();

        // Summary
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("### Services by Category");
        sb.AppendLine();
        sb.AppendLine("| Category | Count | Active | Inactive |");
        sb.AppendLine("|----------|-------|--------|----------|");
        
        foreach (var group in grouped)
        {
            var active = group.Count(s => s.IsActive);
            var inactive = group.Count(s => !s.IsActive);
            sb.AppendLine($"| {group.Key} | {group.Count()} | {active} | {inactive} |");
        }
        sb.AppendLine();

        // Services by Category
        foreach (var group in grouped)
        {
            sb.AppendLine($"## {group.Key}");
            sb.AppendLine();
            sb.AppendLine($"_{group.Count()} services in this category_");
            sb.AppendLine();

            sb.AppendLine("| Code | Service Name | Status | Description |");
            sb.AppendLine("|------|--------------|--------|-------------|");
            
            foreach (var service in group.OrderBy(s => s.ServiceCode))
            {
                var status = service.IsActive ? "✅ Active" : "❌ Inactive";
                var description = Truncate(service.Description, 60);
                sb.AppendLine($"| `{service.ServiceCode}` | **{service.ServiceName}** | {status} | {description} |");
            }
            sb.AppendLine();

            // Detailed list
            if (data.IncludeDetails)
            {
                sb.AppendLine("### Service Details");
                sb.AppendLine();
                
                foreach (var service in group.OrderBy(s => s.ServiceCode))
                {
                    sb.AppendLine($"#### {service.ServiceName}");
                    sb.AppendLine();
                    sb.AppendLine($"- **Code:** `{service.ServiceCode}`");
                    sb.AppendLine($"- **Version:** {service.Version ?? "1.0.0"}");
                    sb.AppendLine($"- **Status:** {(service.IsActive ? "Active" : "Inactive")}");
                    if (!string.IsNullOrEmpty(service.Description))
                    {
                        sb.AppendLine();
                        sb.AppendLine(service.Description);
                    }
                    sb.AppendLine();
                }
            }
        }

        // Index
        sb.AppendLine("## Alphabetical Index");
        sb.AppendLine();
        
        foreach (var service in services.OrderBy(s => s.ServiceName))
        {
            sb.AppendLine($"- **{service.ServiceName}** (`{service.ServiceCode}`) - {service.CategoryName ?? "Uncategorized"}");
        }
        sb.AppendLine();

        // Footer
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"_Generated by Service Catalogue Manager on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC_");
        
        if (!string.IsNullOrEmpty(data.Organization))
            sb.AppendLine($"_© {DateTime.UtcNow.Year} {data.Organization}_");

        return sb.ToString();
    }

    private static string Truncate(string? text, int maxLength)
    {
        if (string.IsNullOrEmpty(text)) return "-";
        text = text.Replace("\n", " ").Replace("\r", "").Replace("|", "\\|");
        return text.Length <= maxLength ? text : text[..(maxLength - 3)] + "...";
    }
}

public class CatalogMarkdownData
{
    public string? CatalogTitle { get; set; }
    public string? Organization { get; set; }
    public bool IncludeDetails { get; set; } = true;
    public IEnumerable<CatalogServiceMdSummary>? Services { get; set; }
}

public class CatalogServiceMdSummary
{
    public int ServiceId { get; set; }
    public string ServiceCode { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? CategoryName { get; set; }
    public bool IsActive { get; set; }
    public string? Version { get; set; }
}
