# =============================================================================
# RUN UNIT TESTS JOB TEMPLATE
# Service Catalogue Manager - Azure DevOps Pipeline
# =============================================================================

parameters:
  - name: frontendWorkingDirectory
    type: string
    default: 'src/frontend'
  - name: backendWorkingDirectory
    type: string
    default: 'src/backend'
  - name: nodeVersion
    type: string
    default: '20.x'
  - name: dotnetVersion
    type: string
    default: '8.x'
  - name: publishTestResults
    type: boolean
    default: true
  - name: publishCodeCoverage
    type: boolean
    default: true
  - name: minimumCoverage
    type: number
    default: 70

jobs:
  - job: RunUnitTests
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
      # Setup Node.js for frontend tests
      - template: ../steps/setup-node.yml
        parameters:
          nodeVersion: ${{ parameters.nodeVersion }}

      # Setup .NET for backend tests
      - template: ../steps/setup-dotnet.yml
        parameters:
          dotnetVersion: ${{ parameters.dotnetVersion }}

      # ==================== FRONTEND TESTS ====================
      
      # Install frontend dependencies
      - task: Npm@1
        displayName: 'Install Frontend Dependencies'
        inputs:
          command: 'ci'
          workingDir: ${{ parameters.frontendWorkingDirectory }}

      # Run frontend unit tests with coverage
      - task: Npm@1
        displayName: 'Run Frontend Unit Tests'
        inputs:
          command: 'custom'
          workingDir: ${{ parameters.frontendWorkingDirectory }}
          customCommand: 'run test:coverage'
        continueOnError: true

      # Publish frontend test results
      - ${{ if eq(parameters.publishTestResults, true) }}:
        - task: PublishTestResults@2
          displayName: 'Publish Frontend Test Results'
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '${{ parameters.frontendWorkingDirectory }}/coverage/junit.xml'
            testRunTitle: 'Frontend Unit Tests'
            failTaskOnFailedTests: true
          condition: always()

      # Publish frontend code coverage
      - ${{ if eq(parameters.publishCodeCoverage, true) }}:
        - task: PublishCodeCoverageResults@1
          displayName: 'Publish Frontend Coverage'
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '${{ parameters.frontendWorkingDirectory }}/coverage/cobertura-coverage.xml'
            reportDirectory: '${{ parameters.frontendWorkingDirectory }}/coverage/lcov-report'
          condition: always()

      # ==================== BACKEND TESTS ====================

      # Restore backend dependencies
      - task: DotNetCoreCLI@2
        displayName: 'Restore Backend Dependencies'
        inputs:
          command: 'restore'
          projects: '${{ parameters.backendWorkingDirectory }}/**/*.Tests.csproj'

      # Run backend unit tests with coverage
      - task: DotNetCoreCLI@2
        displayName: 'Run Backend Unit Tests'
        inputs:
          command: 'test'
          projects: '${{ parameters.backendWorkingDirectory }}/**/*.Tests.csproj'
          arguments: '--configuration Release --collect:"XPlat Code Coverage" --results-directory $(Agent.TempDirectory)/TestResults --filter "Category!=Integration"'
          publishTestResults: ${{ parameters.publishTestResults }}
        continueOnError: true

      # Publish backend code coverage
      - ${{ if eq(parameters.publishCodeCoverage, true) }}:
        - task: PublishCodeCoverageResults@1
          displayName: 'Publish Backend Coverage'
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'
          condition: always()

      # Check coverage threshold
      - script: |
          echo "Checking code coverage threshold (${{ parameters.minimumCoverage }}%)"
          # Coverage threshold validation would be done here
          echo "##vso[task.setvariable variable=unitTestsCompleted;isOutput=true]true"
        displayName: 'Validate Coverage Threshold'
        name: coverageCheck
