using System.Text;
using System.Text.Json;

namespace ServiceCatalogueManager.Api.Templates.UuBookKit;

/// <summary>
/// Generates Uu5 page content for UuBookKit documentation system
/// </summary>
public class Uu5PageTemplate
{
    public static string GenerateServicePage(Uu5ServicePageData data)
    {
        var sb = new StringBuilder();

        // Page header with metadata
        sb.AppendLine("<!--UU5_PAGE_SETTINGS-->");
        sb.AppendLine($"<!--title={data.ServiceName}-->");
        sb.AppendLine($"<!--code={data.ServiceCode}-->");
        sb.AppendLine("<!--/UU5_PAGE_SETTINGS-->");
        sb.AppendLine();

        // Main header
        sb.AppendLine($"<UU5.Bricks.Header level=\"1\">{EscapeUu5(data.ServiceName)}</UU5.Bricks.Header>");
        sb.AppendLine();

        // Info panel
        sb.AppendLine("<UU5.Bricks.Panel header=\"Service Information\" colorSchema=\"blue\">");
        sb.AppendLine("  <UU5.Bricks.Row>");
        sb.AppendLine("    <UU5.Bricks.Column colWidth=\"xs-12 m-6\">");
        sb.AppendLine($"      <UU5.Bricks.Lsi><UU5.Bricks.Strong>Service Code:</UU5.Bricks.Strong> {EscapeUu5(data.ServiceCode)}</UU5.Bricks.Lsi>");
        sb.AppendLine($"      <UU5.Bricks.Lsi><UU5.Bricks.Strong>Version:</UU5.Bricks.Strong> {EscapeUu5(data.Version ?? "1.0.0")}</UU5.Bricks.Lsi>");
        sb.AppendLine($"      <UU5.Bricks.Lsi><UU5.Bricks.Strong>Category:</UU5.Bricks.Strong> {EscapeUu5(data.CategoryName ?? "N/A")}</UU5.Bricks.Lsi>");
        sb.AppendLine("    </UU5.Bricks.Column>");
        sb.AppendLine("    <UU5.Bricks.Column colWidth=\"xs-12 m-6\">");
        sb.AppendLine($"      <UU5.Bricks.Badge colorSchema=\"{(data.IsActive ? "success" : "danger")}\">{(data.IsActive ? "Active" : "Inactive")}</UU5.Bricks.Badge>");
        sb.AppendLine($"      <UU5.Bricks.Lsi><UU5.Bricks.Strong>Last Updated:</UU5.Bricks.Strong> {data.ModifiedDate?.ToString("yyyy-MM-dd") ?? "N/A"}</UU5.Bricks.Lsi>");
        sb.AppendLine("    </UU5.Bricks.Column>");
        sb.AppendLine("  </UU5.Bricks.Row>");
        sb.AppendLine("</UU5.Bricks.Panel>");
        sb.AppendLine();

        // Description
        if (!string.IsNullOrEmpty(data.Description))
        {
            sb.AppendLine("<UU5.Bricks.Section header=\"Overview\">");
            sb.AppendLine($"  <UU5.Bricks.P>{EscapeUu5(data.Description)}</UU5.Bricks.P>");
            sb.AppendLine("</UU5.Bricks.Section>");
            sb.AppendLine();
        }

        // Usage Scenarios
        if (data.UsageScenarios?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GenerateUsageScenarios(data.UsageScenarios));
        }

        // Dependencies
        if (data.Dependencies?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GenerateDependencies(data.Dependencies));
        }

        // Scope
        if (data.InScopeItems?.Any() == true || data.OutOfScopeItems?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GenerateScope(data.InScopeItems, data.OutOfScopeItems));
        }

        // Prerequisites
        if (data.Prerequisites?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GeneratePrerequisites(data.Prerequisites));
        }

        // Tools
        if (data.Tools?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GenerateTools(data.Tools));
        }

        // Inputs/Outputs
        if (data.Inputs?.Any() == true || data.Outputs?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GenerateInputsOutputs(data.Inputs, data.Outputs));
        }

        // Timeline
        if (data.TimelinePhases?.Any() == true)
        {
            sb.AppendLine(Uu5SectionTemplates.GenerateTimeline(data.TimelinePhases));
        }

        // Footer
        sb.AppendLine("<UU5.Bricks.Div className=\"uu5-common-right\">");
        sb.AppendLine($"  <UU5.Bricks.Small>Generated by Service Catalogue Manager • {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC</UU5.Bricks.Small>");
        sb.AppendLine("</UU5.Bricks.Div>");

        return sb.ToString();
    }

    public static string GenerateCatalogIndex(Uu5CatalogIndexData data)
    {
        var sb = new StringBuilder();
        var services = data.Services?.ToList() ?? new List<Uu5ServiceSummary>();

        sb.AppendLine("<!--UU5_PAGE_SETTINGS-->");
        sb.AppendLine($"<!--title={data.CatalogTitle ?? "Service Catalogue"}-->");
        sb.AppendLine("<!--/UU5_PAGE_SETTINGS-->");
        sb.AppendLine();

        sb.AppendLine($"<UU5.Bricks.Header level=\"1\">{EscapeUu5(data.CatalogTitle ?? "Service Catalogue")}</UU5.Bricks.Header>");
        sb.AppendLine();

        // Statistics
        sb.AppendLine("<UU5.Bricks.Row>");
        sb.AppendLine("  <UU5.Bricks.Column colWidth=\"xs-6 m-3\">");
        sb.AppendLine($"    <UU5.Bricks.Well colorSchema=\"blue\"><UU5.Bricks.Header level=\"2\">{services.Count}</UU5.Bricks.Header><UU5.Bricks.P>Total Services</UU5.Bricks.P></UU5.Bricks.Well>");
        sb.AppendLine("  </UU5.Bricks.Column>");
        sb.AppendLine("  <UU5.Bricks.Column colWidth=\"xs-6 m-3\">");
        sb.AppendLine($"    <UU5.Bricks.Well colorSchema=\"success\"><UU5.Bricks.Header level=\"2\">{services.Count(s => s.IsActive)}</UU5.Bricks.Header><UU5.Bricks.P>Active</UU5.Bricks.P></UU5.Bricks.Well>");
        sb.AppendLine("  </UU5.Bricks.Column>");
        sb.AppendLine("  <UU5.Bricks.Column colWidth=\"xs-6 m-3\">");
        sb.AppendLine($"    <UU5.Bricks.Well colorSchema=\"danger\"><UU5.Bricks.Header level=\"2\">{services.Count(s => !s.IsActive)}</UU5.Bricks.Header><UU5.Bricks.P>Inactive</UU5.Bricks.P></UU5.Bricks.Well>");
        sb.AppendLine("  </UU5.Bricks.Column>");
        sb.AppendLine("  <UU5.Bricks.Column colWidth=\"xs-6 m-3\">");
        sb.AppendLine($"    <UU5.Bricks.Well colorSchema=\"grey\"><UU5.Bricks.Header level=\"2\">{services.Select(s => s.CategoryName).Distinct().Count()}</UU5.Bricks.Header><UU5.Bricks.P>Categories</UU5.Bricks.P></UU5.Bricks.Well>");
        sb.AppendLine("  </UU5.Bricks.Column>");
        sb.AppendLine("</UU5.Bricks.Row>");
        sb.AppendLine();

        // Services by category
        var grouped = services.GroupBy(s => s.CategoryName ?? "Uncategorized").OrderBy(g => g.Key);
        foreach (var group in grouped)
        {
            sb.AppendLine($"<UU5.Bricks.Section header=\"{EscapeUu5(group.Key)}\">");
            sb.AppendLine("  <UU5.Bricks.Table striped>");
            sb.AppendLine("    <UU5.Bricks.Table.THead>");
            sb.AppendLine("      <UU5.Bricks.Table.Tr>");
            sb.AppendLine("        <UU5.Bricks.Table.Th>Code</UU5.Bricks.Table.Th>");
            sb.AppendLine("        <UU5.Bricks.Table.Th>Service Name</UU5.Bricks.Table.Th>");
            sb.AppendLine("        <UU5.Bricks.Table.Th>Status</UU5.Bricks.Table.Th>");
            sb.AppendLine("      </UU5.Bricks.Table.Tr>");
            sb.AppendLine("    </UU5.Bricks.Table.THead>");
            sb.AppendLine("    <UU5.Bricks.Table.TBody>");
            
            foreach (var service in group.OrderBy(s => s.ServiceCode))
            {
                var statusColor = service.IsActive ? "success" : "danger";
                var statusText = service.IsActive ? "Active" : "Inactive";
                sb.AppendLine("      <UU5.Bricks.Table.Tr>");
                sb.AppendLine($"        <UU5.Bricks.Table.Td><UU5.Bricks.Code>{EscapeUu5(service.ServiceCode)}</UU5.Bricks.Code></UU5.Bricks.Table.Td>");
                sb.AppendLine($"        <UU5.Bricks.Table.Td><UU5.Bricks.Link href=\"{service.PageUrl}\">{EscapeUu5(service.ServiceName)}</UU5.Bricks.Link></UU5.Bricks.Table.Td>");
                sb.AppendLine($"        <UU5.Bricks.Table.Td><UU5.Bricks.Badge colorSchema=\"{statusColor}\">{statusText}</UU5.Bricks.Badge></UU5.Bricks.Table.Td>");
                sb.AppendLine("      </UU5.Bricks.Table.Tr>");
            }
            
            sb.AppendLine("    </UU5.Bricks.Table.TBody>");
            sb.AppendLine("  </UU5.Bricks.Table>");
            sb.AppendLine("</UU5.Bricks.Section>");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    public static string EscapeUu5(string? text)
    {
        if (string.IsNullOrEmpty(text)) return string.Empty;
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");
    }
}

public class Uu5ServicePageData
{
    public string ServiceName { get; set; } = string.Empty;
    public string ServiceCode { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Version { get; set; }
    public bool IsActive { get; set; }
    public string? CategoryName { get; set; }
    public DateTime? ModifiedDate { get; set; }
    
    public IEnumerable<Uu5UsageScenario>? UsageScenarios { get; set; }
    public IEnumerable<Uu5Dependency>? Dependencies { get; set; }
    public IEnumerable<string>? InScopeItems { get; set; }
    public IEnumerable<string>? OutOfScopeItems { get; set; }
    public IEnumerable<Uu5Prerequisite>? Prerequisites { get; set; }
    public IEnumerable<Uu5Tool>? Tools { get; set; }
    public IEnumerable<Uu5Input>? Inputs { get; set; }
    public IEnumerable<Uu5Output>? Outputs { get; set; }
    public IEnumerable<Uu5TimelinePhase>? TimelinePhases { get; set; }
}

public class Uu5CatalogIndexData
{
    public string? CatalogTitle { get; set; }
    public IEnumerable<Uu5ServiceSummary>? Services { get; set; }
}

public class Uu5ServiceSummary
{
    public string ServiceCode { get; set; } = string.Empty;
    public string ServiceName { get; set; } = string.Empty;
    public string? CategoryName { get; set; }
    public bool IsActive { get; set; }
    public string? PageUrl { get; set; }
}

// Data models for Uu5
public record Uu5UsageScenario(string Name, string? Description, string? Actors, int SortOrder);
public record Uu5Dependency(string Name, string? Type, string? Criticality, int SortOrder);
public record Uu5Prerequisite(string Name, bool IsMandatory, string? Description, int SortOrder);
public record Uu5Tool(string Name, string? Category, string? Version, int SortOrder);
public record Uu5Input(string Name, string? DataType, bool IsRequired, int SortOrder);
public record Uu5Output(string Name, string? DataType, string? Format, int SortOrder);
public record Uu5TimelinePhase(string Name, int DurationDays, int SortOrder);
